-- =====================================================
-- LIBRO DIGITAL — academicService
-- Base de datos: librodigital_academic
-- Puerto del servicio: 8092
-- =====================================================
-- Conectarse a librodigital_academic antes de ejecutar.
-- Sin FK a authService: user_id es referencia lógica por ID.
-- =====================================================

CREATE TABLE IF NOT EXISTS guardians (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut              VARCHAR(255) NOT NULL UNIQUE,
    first_name       VARCHAR(255) NOT NULL,
    last_name        VARCHAR(255) NOT NULL,
    second_last_name VARCHAR(255),
    email            VARCHAR(255) NOT NULL UNIQUE,
    phone            VARCHAR(255) NOT NULL,
    emergency_phone  VARCHAR(255),
    address          VARCHAR(255),
    commune          VARCHAR(255),
    city             VARCHAR(255),
    relationship     VARCHAR(255) NOT NULL,
    occupation       VARCHAR(255),
    workplace        VARCHAR(255),
    work_phone       VARCHAR(255),
    is_primary       BOOLEAN NOT NULL DEFAULT TRUE,
    user_id          BIGINT,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teachers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut              VARCHAR(255) NOT NULL UNIQUE,
    first_name       VARCHAR(255) NOT NULL,
    last_name        VARCHAR(255) NOT NULL,
    second_last_name VARCHAR(255),
    email            VARCHAR(255) NOT NULL UNIQUE,
    phone            VARCHAR(255),
    address          VARCHAR(255),
    commune          VARCHAR(255),
    city             VARCHAR(255),
    employee_number  VARCHAR(255) UNIQUE,
    specialization   VARCHAR(255),
    education_level  VARCHAR(255),
    hire_date        DATE,
    contract_type    VARCHAR(255),
    teacher_status   VARCHAR(255) NOT NULL DEFAULT 'ACTIVO',
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut               VARCHAR(255) NOT NULL,
    first_name        VARCHAR(255) NOT NULL,
    second_name       VARCHAR(255),
    last_name         VARCHAR(255) NOT NULL,
    mother_last_name  VARCHAR(255),
    email             VARCHAR(255),
    phone             VARCHAR(255),
    address           VARCHAR(255),
    commune           VARCHAR(255),
    city              VARCHAR(255),
    date_of_birth     DATE,
    enrollment_number VARCHAR(255) UNIQUE,
    student_status    VARCHAR(255) NOT NULL DEFAULT 'ACTIVO',
    admission_date    DATE,
    withdrawal_date   DATE,
    guardian_id       BIGINT,
    user_id           BIGINT,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    grade            VARCHAR(255) NOT NULL,
    academic_year    DATE NOT NULL,
    shift            VARCHAR(255),
    head_teacher_id  BIGINT,
    max_capacity     INTEGER,
    classroom        VARCHAR(255),
    level            VARCHAR(255),
    course_status    VARCHAR(255) NOT NULL DEFAULT 'ACTIVO',
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subjects (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_name  VARCHAR(255),
    subject_code  VARCHAR(255),
    description   VARCHAR(255),
    subject_type  VARCHAR(255),
    weekly_hours  INTEGER,
    teacher_id    BIGINT,
    course_id     BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS enrollments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        BIGINT,
    course_id         BIGINT,
    enrollment_date   DATE,
    academic_year     INTEGER,
    enrollment_status VARCHAR(255),
    is_regular        BOOLEAN,
    observations      VARCHAR(255),
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);

CREATE TABLE IF NOT EXISTS evaluations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id        BIGINT,
    course_id         BIGINT,
    name              VARCHAR(255),
    date              DATE,
    evaluation_type   VARCHAR(255),
    evaluation_status VARCHAR(255),
    max_score         DOUBLE PRECISION,
    weight            DOUBLE PRECISION,
    description       VARCHAR(255),
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);

CREATE TABLE IF NOT EXISTS grades (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id           BIGINT NOT NULL,
    evaluation_id        BIGINT NOT NULL,
    subject_id           BIGINT NOT NULL,
    score                NUMERIC(5,2) NOT NULL,
    grade_date           DATE NOT NULL,
    grade_status         VARCHAR(255) NOT NULL DEFAULT 'DEFINITIVA',
    teacher_comments     VARCHAR(1000),
    is_absent            BOOLEAN DEFAULT FALSE,
    graded_by_teacher_id BIGINT,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP
);

-- =====================================================
-- Datos de prueba (instalación nueva)
-- =====================================================

INSERT INTO teachers (rut, first_name, last_name, email, teacher_status, created_at, updated_at)
SELECT '11.111.111-1', 'Manuel', 'García', 'manuel@colegio.cl', 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM teachers WHERE rut = '11.111.111-1');

INSERT INTO guardians (rut, first_name, last_name, email, phone, relationship, is_primary, created_at, updated_at)
SELECT '98765432-1', 'María', 'Pérez', 'maria@correo.cl', '+56912345678', 'MADRE', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM guardians WHERE rut = '98765432-1');

INSERT INTO students (rut, first_name, last_name, mother_last_name, email, student_status, guardian_id, created_at)
SELECT '12345678-9', 'Juan', 'Pérez', 'López', 'juan@correo.cl', 'ACTIVO',
       (SELECT id FROM guardians WHERE rut = '98765432-1' LIMIT 1),
       CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM students WHERE rut = '12345678-9');

INSERT INTO courses (name, grade, academic_year, course_status, created_at, updated_at)
SELECT '1° Medio', '1° Medio', DATE '2026-03-01', 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE name = '1° Medio');

INSERT INTO subjects (subject_name, subject_code, course_id, teacher_id, created_at, updated_at)
SELECT 'Matemáticas', 'MAT-101',
       (SELECT id FROM courses WHERE name = '1° Medio' LIMIT 1),
       (SELECT id FROM teachers WHERE rut = '11.111.111-1' LIMIT 1),
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM subjects WHERE subject_code = 'MAT-101');

INSERT INTO enrollments (student_id, course_id, enrollment_date, academic_year, is_regular, enrollment_status, created_at, updated_at)
SELECT
    (SELECT id FROM students WHERE rut = '12345678-9' LIMIT 1),
    (SELECT id FROM courses WHERE name = '1° Medio' LIMIT 1),
    CURRENT_DATE, 2026, TRUE, 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM enrollments e
    JOIN students s ON s.id = e.student_id AND s.rut = '12345678-9'
);

INSERT INTO evaluations (name, date, subject_id, course_id, max_score, weight, evaluation_type, evaluation_status, created_at, updated_at)
SELECT 'Prueba 1', CURRENT_DATE,
       (SELECT id FROM subjects WHERE subject_code = 'MAT-101' LIMIT 1),
       (SELECT id FROM courses WHERE name = '1° Medio' LIMIT 1),
       7.0, 30.0, 'PRUEBA', 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM evaluations WHERE name = 'Prueba 1');

INSERT INTO grades (student_id, evaluation_id, subject_id, score, grade_date, grade_status, graded_by_teacher_id, created_at, updated_at)
SELECT
    (SELECT id FROM students WHERE rut = '12345678-9' LIMIT 1),
    (SELECT id FROM evaluations WHERE name = 'Prueba 1' LIMIT 1),
    (SELECT id FROM subjects WHERE subject_code = 'MAT-101' LIMIT 1),
    6.5, CURRENT_DATE, 'DEFINITIVA',
    (SELECT id FROM teachers WHERE rut = '11.111.111-1' LIMIT 1),
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM grades g
    JOIN students s ON s.id = g.student_id AND s.rut = '12345678-9'
    JOIN evaluations e ON e.id = g.evaluation_id AND e.name = 'Prueba 1'
);
