-- =====================================================
-- LIBRO DIGITAL — attendanceService
-- Base de datos: librodigital_attendance
-- Puerto del servicio: 8093
-- =====================================================
-- Conectarse a librodigital_attendance antes de ejecutar.
-- course_id, subject_id, teacher_id, student_id son referencias
-- lógicas al academicService (sin foreign keys entre bases).
-- =====================================================

CREATE TABLE IF NOT EXISTS class_sessions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id      BIGINT NOT NULL,
    subject_id     BIGINT NOT NULL,
    teacher_id     BIGINT NOT NULL,
    session_date   DATE NOT NULL,
    topic          VARCHAR(255),
    session_status VARCHAR(255) DEFAULT 'ABIERTA',
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance_records (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL,
    student_id   BIGINT NOT NULL,
    status       VARCHAR(255) NOT NULL DEFAULT 'PRESENTE',
    observations VARCHAR(255),
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT uk_attendance_session_student UNIQUE (session_id, student_id)
);

CREATE TABLE IF NOT EXISTS annotations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL,
    teacher_id      BIGINT NOT NULL,
    annotation_date DATE NOT NULL,
    type            VARCHAR(255) NOT NULL,
    description     VARCHAR(255),
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

-- =====================================================
-- Datos de prueba
-- Usa IDs existentes en librodigital_academic en tu entorno.
-- Ajusta los SELECT si tus IDs son distintos.
-- =====================================================

-- Sesión de clase (curso 17, asignatura 2, docente 1 — datos actuales del proyecto)
INSERT INTO class_sessions (course_id, subject_id, teacher_id, session_date, topic, session_status, created_at, updated_at)
SELECT 17, 2, 1, CURRENT_DATE, 'Ecuaciones lineales', 'ABIERTA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM class_sessions
    WHERE course_id = 17 AND subject_id = 2 AND session_date = CURRENT_DATE
);

-- Asistencia del estudiante Juan (id 2)
INSERT INTO attendance_records (session_id, student_id, status, created_at, updated_at)
SELECT cs.id, 2, 'PRESENTE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM class_sessions cs
WHERE cs.course_id = 17 AND cs.subject_id = 2 AND cs.session_date = CURRENT_DATE
  AND NOT EXISTS (
      SELECT 1 FROM attendance_records ar
      WHERE ar.session_id = cs.id AND ar.student_id = 2
  );

-- Anotación positiva
INSERT INTO annotations (student_id, teacher_id, annotation_date, type, description, created_at, updated_at)
SELECT 2, 1, CURRENT_DATE, 'POSITIVA', 'Participación activa en clase', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM annotations
    WHERE student_id = 2 AND teacher_id = 1 AND annotation_date = CURRENT_DATE AND type = 'POSITIVA'
);
