-- =====================================================
-- 📚 LIBRO DE CLASES DIGITAL - SCRIPT DE BASE DE DATOS
-- =====================================================
--
-- 🧾 INSTRUCCIONES DE USO
--
-- 1. Crear una base de datos en PostgreSQL:
--    CREATE DATABASE libro_clases;
--
-- 2. Conectarse a la base de datos creada
--
-- 3. Ejecutar este script completo para:
--    ✅ Crear tablas
--    ✅ Definir relaciones (FK)
--    ✅ Insertar datos de prueba
--
-- ⚠️ IMPORTANTE:
-- Este script está diseñado para PostgreSQL
-- Compatible con pgAdmin, DBeaver o psql
--
-- =====================================================
``
-- =========================================
-- BASE DE DATOS: LIBRO DE CLASES DIGITAL
-- =========================================

-- =========================
-- TABLA: TEACHERS
-- =========================
CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    second_last_name VARCHAR(100),
    email VARCHAR(150) UNIQUE,
    phone VARCHAR(50),
    address VARCHAR(255),
    city VARCHAR(100),
    commune VARCHAR(100),
    rut VARCHAR(20) UNIQUE,
    employee_number VARCHAR(50),
    contract_type VARCHAR(50),
    education_level VARCHAR(100),
    specialization VARCHAR(100),
    teacher_status VARCHAR(50),
    hire_date DATE,
    user_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- =========================
-- TABLA: STUDENTS
-- =========================
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100),
    second_name VARCHAR(100),
    last_name VARCHAR(100),
    mother_last_name VARCHAR(100),
    name VARCHAR(150),
    email VARCHAR(150),
    phone VARCHAR(50),
    address VARCHAR(255),
    city VARCHAR(100),
    commune VARCHAR(100),
    rut VARCHAR(20),
    enrollment_number VARCHAR(50),
    guardian_id BIGINT,
    user_id BIGINT,
    blood_type VARCHAR(10),
    allergies VARCHAR(255),
    medical_conditions VARCHAR(255),
    emergency_medication VARCHAR(255),
    admission_date DATE,
    withdrawal_date DATE,
    date_of_birth DATE,
    student_status VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- =========================
-- TABLA: COURSES
-- =========================
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    teacher_id BIGINT,
    head_teacher_id BIGINT,
    year INTEGER,
    academic_year DATE,
    level VARCHAR(50),
    grade VARCHAR(50),
    classroom VARCHAR(100),
    shift VARCHAR(50),
    max_capacity INTEGER,
    course_status VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_course_teacher
        FOREIGN KEY (teacher_id)
        REFERENCES teachers(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_head_teacher
        FOREIGN KEY (head_teacher_id)
        REFERENCES teachers(id)
        ON DELETE SET NULL
);

-- =========================
-- TABLA: SUBJECTS
-- =========================
CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    course_id BIGINT,
    CONSTRAINT fk_subject_course
        FOREIGN KEY (course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE
);

-- =========================
-- TABLA: ENROLLMENTS
-- =========================
CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    course_id BIGINT,
    enrollment_date DATE,
    academic_year INTEGER,
    is_regular BOOLEAN,
    enrollment_status VARCHAR(50),
    observations VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES students(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_enrollment_course
        FOREIGN KEY (course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE
);

-- =========================
-- TABLA: EVALUATIONS
-- =========================
CREATE TABLE evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    date DATE,
    subject_id BIGINT,
    course_id BIGINT,
    description VARCHAR(255),
    evaluation_type VARCHAR(50),
    evaluation_status VARCHAR(50),
    max_score DOUBLE PRECISION,
    weight DOUBLE PRECISION,
    grade DOUBLE PRECISION,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_evaluation_subject
        FOREIGN KEY (subject_id)
        REFERENCES subjects(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_evaluation_course
        FOREIGN KEY (course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE
);

-- =========================================
-- DATOS DE PRUEBA
-- =========================================

INSERT INTO teachers (
    first_name, last_name, email, teacher_status, created_at
) VALUES (
    'Juan', 'Perez', 'juan@colegio.cl', 'ACTIVO', CURRENT_TIMESTAMP
);

INSERT INTO students (
    first_name, last_name, email, student_status, created_at
) VALUES (
    'Maria', 'Gomez', 'maria@correo.cl', 'ACTIVO', CURRENT_TIMESTAMP
);

INSERT INTO courses (
    name, teacher_id, year, course_status, created_at
) VALUES (
    '1A', 1, 2026, 'ACTIVO', CURRENT_TIMESTAMP
);

INSERT INTO subjects (name, course_id)
VALUES ('Matematica', 1);

INSERT INTO enrollments (
    student_id, course_id, enrollment_date, academic_year, is_regular
) VALUES (
    1, 1, CURRENT_DATE, 2026, true
);

INSERT INTO evaluations (
    name, date, subject_id, course_id, max_score, grade
) VALUES (
    'Prueba 1', CURRENT_DATE, 1, 1, 7.0, 6.5
);

-- =====================================================
-- ✅ SCRIPT EJECUTADO CORRECTAMENTE
-- Base de datos lista para uso
-- =====================================================
``